module.exports = [
  'Account ID',
  'Account',
  'Campaign ID',
  'Campaign Name',
  'Ad Set ID',
  'Ad Set Name',
  'Ends',
  'Starts',
  'Reporting Starts',
  'Reporting Ends',
  'Budget',
  'Budget Type',
  'Bid',
  'Bid Type',
  'Reach',
  'Impressions',
  'Frequency',
  'Delivery',
  'Clicks (All)',
  'CPC (All) (USD)',
  'CTR (All)',
  'Unique Clicks (All)',
  'Unique CTR (Link)',
  'View Content Conversion Value (Facebook Pixel)',
  'Cost per Mobile App Feature Unlock (USD)',
  'Mobile App Searches',
  'Video Views to 50%',
  'Mobile App Actions Conversion Value',
  'Cost per Page Mention (USD)',
  'Other Mobile App Actions',
  'Video Views to 75%',
  'Event Responses',
  'Cost per Mobile App Search (USD)',
  'Cost per Mobile App Credit Spend (USD)',
  'Mobile App Actions',
  'Result Rate (USD)',
  'Results',
  'Result Type',
  'Add Payment Info Conversion Value (Facebook Pixel)',
  'Estimated Ad Recall Lift (People)',
  'Cost per Purchase (Facebook Pixel) (USD)',
  'Cost per Gift Sale (USD)',
  'Mobile App Content Views',
  'CPC (Link) (USD)',
  'Mobile App Starts',
  'Post Comments',
  'Cost per App Use (USD)',
  'Post Shares',
  'Avg',
  'View Content (Facebook Pixel)',
  'Unique CTR (All)',
  '10-Second Views',
  'Credit Spends Conversion Value',
  'Unique Social Clicks (All)',
  'Cost per Mobile App Start (USD)',
  'Mobile App Credit Spends',
  'People Taking Action',
  'Unique Clicks to Link',
  'Cost per App Story Engagement (USD)',
  'Initiate Checkout (Facebook Pixel)',
  'Add to Cart Conversion Value (Facebook Pixel)',
  'Cost per Question Answer (USD)',
  'Cost per Credit Spend Action (USD)',
  'Add Payment Info (Facebook Pixel)',
  'Mobile App Purchases Conversion Value',
  'Cost per App Install (USD)',
  'Mobile App Achievements',
  'App Uses',
  'Cost per Unique Click (All) (USD)',
  'Mobile App Ratings Conversion Value',
  'Mobile App Registrations',
  'Cost per 10-Second View (USD)',
  'Complete Registration (Facebook Pixel)',
  'Cost per App Engagement (USD)',
  'App Installs',
  'Video Views to 25%',
  'Offer Claims',
  'App Engagement',
  'Cost per Add to Wishlist (Facebook Pixel) (USD)',
  'Link Clicks',
  'Cost per Mobile App Tutorial Completion (USD)',
  'Mobile App Tutorial Completions',
  'Mobile App Adds to Cart Conversion Value',
  'Cost per Page Tab View (USD)',
  'Cost per Add Payment Info (Facebook Pixel) (USD)',
  'Mobile App Ratings',
  'Cost per Mobile App Payment Detail (USD)',
  'Purchase Conversion Value (Facebook Pixel)',
  'Cost per Mobile App Registration (USD)',
  'Video Views to 100%',
  'Mobile App Adds to Cart',
  'Cost per Mobile App Content View (USD)',
  'Social Reach',
  'Mobile App Adds to Wishlist',
  'Cost per Complete Registration (Facebook Pixel) (USD)',
  'Social Clicks (All)',
  'Cost per Mobile App Checkout (USD)',
  'Clicks to Play Video',
  'Mobile App Installs',
  'Cost per Photo View (USD)',
  'Video Views to 95%',
  'Page Tab Views',
  'Cost per View Content (Facebook Pixel) (USD)',
  'Initiate Checkout Conversion Value (Facebook Pixel)',
  'Question Follows',
  'Cost per Offer Claim (USD)',
  'Search Conversion Value (Facebook Pixel)',
  'Cost per Mobile App Add to Cart (USD)',
  'Add to Wishlist (Facebook Pixel)',
  'Mobile App Payment Details',
  'Gift Sales',
  'Page Mentions',
  'Cost per Mobile App Achievement (USD)',
  'Mobile App Checkouts',
  'Cost per Mobile App Add to Wishlist (USD)',
  'Cost per Website Action (All) (USD)',
  'Website Actions (All)',
  'Cost per Mobile App Purchase (USD)',
  'Cost per Add to Cart (Facebook Pixel) (USD)',
  'Cost per Post Like (USD)',
  'Actions',
  'Mobile App Credit Spends Conversion Value',
  'Add to Cart (Facebook Pixel)',
  'CTR (Link)',
  'Cost per Search (Facebook Pixel) (USD)',
  'Search (Facebook Pixel)',
  'Cost per Game Play (USD)',
  'Mobile App Feature Unlocks',
  'Gift Sales Conversion Value',
  'Cost per Check-In (USD)',
  'Photo Views',
  'Mobile App Checkouts Conversion Value',
  'Cost per Page Like (USD)',
  'Cost per Mobile App Install (USD)',
  'Mobile App Content Views Conversion Value',
  'Cost per Video View (USD)',
  'Total Conversion Value',
  'Cost per Event Response (USD)',
  'Cost per Mobile App Action (USD)',
  'App Story Engagement',
  'Website Action Value (All)',
  '30-Second Views',
  'Video Views',
  'Cost per Post Engagement (USD)',
  'Cost per Post Comment (USD)',
  'Check-Ins',
  'Credit Spends',
  'Mobile App Purchases',
  'Add to Wishlist Conversion Value (Facebook Pixel)',
  'Social Impressions',
  'Lead Conversion Value (Facebook Pixel)',
  'Cost per Page Engagement (USD)',
  'Cost per Mobile App Rating (USD)',
  'Lead (Facebook Pixel)',
  'Cost per Question Follow (USD)',
  'Cost per Initiate Checkout (Facebook Pixel) (USD)',
  'Question Answers',
  'Cost per Other Mobile App Action (USD)',
  'Game Plays',
  'Purchase (Facebook Pixel)',
  'Cost per Lead (Facebook Pixel) (USD)',
  'Cost per Post Share (USD)',
  'Cost per Clicks to Play Video (USD)',
  'Button Clicks',
  'Complete Registration Conversion Value (Facebook Pixel)',
  'Cost per Unique Click to Link (USD)',
  'Cost per Result (USD)',
  'Cost per 1,000 People Reached (USD)',
  'CPM (Cost per 1,000 Impressions) (USD)',
  'Cost per All Actions (USD)',
  'Amount Spent (USD)',
  'Amount Spent Today (USD)',
  'Cost per Estimated Ad Recall Lift (USD)',
  'Page Likes',
  'Page Engagement',
  'Post Engagement',
  'Post Likes',
  'Estimated Ad Recall Lift Rate',
  'Mobile App Adds to Wishlist Conversion Value' ];
